### ISSUE TITLE
Technical Development Roadmap

### ISSUE THREAD

**Issue by m-bystrova** [m-bystrova/learning#29]
- [ ] data structures: Queue, Tree
- [ ] thread and what is process
- [ ] Knows REST principles, HTTP methods, HTTP vs HTTPS, JSON
- [ ] Serialize/deserialize Dates and times (incl. when using REST)
- [ ] functional programming
- [ ] basic design patterns
- [ ] Maven/Gradle
- [ ] Use out-of-the-box JSON/XML serialization tools
- [ ] Basic Reflection knowledge 
- [ ] Knows Threads, Executors API, synchronized. Can read and understand multithreaded code
- [ ] Basic knowledge of how GC works
- [ ] Knows how Docker and Docker Compose works, basic commands and terms
- [ ] Work with a project that uses Hibernate
- [ ] Uses basic commands like less, grep, tail, head, find

---

- [ ] Understanding basic concepts of SOLID and ACID
- [ ] Understanding of FIFO and LIFO principles
- [ ] Knows non-standard data structures like Table, Graph (Guava)
- [ ] Knows how to use Blocking queues. Priority queues.
- [ ] Can explain how Creational Design Patterns can be used in real projects. Factory, Abstract Factory and etc.
- [ ] Experience in all types of design patterns (Creational, Structural, Behavioral) in real projects.
- [ ] Can configure projects with Maven/Gradle Configure additional plugins.
- [ ] Understands Maven/Gradle properties and profiles, can introduce and support conditional build steps
- [ ] Strings memory allocation
- [ ] Optimize code designs by using OOP principles
- [ ] Know serialization process concept
- [ ] Knows when volatile should be used. Understands locks and their behaviour. 
- [ ] Can describe about stages and levels of garbage collection
- [ ] Have basic knowledge of NoSQL and differences between SQL and NoSQL
- [ ] Advanced Indexes knowledge
- [ ] Create custom images. Create docker-compose configurations. Read logs from container. Attach volumes
- [ ] Add Hibernate entities, uses Repository, creates queries
- [ ] Configure static code analysis tool
- [ ] Have experience in designing of REST  API methods from scratch, Open API 2/3, Swagger, Jackson
- [ ] OAuth knowledge Configure & use OAuth for project Knowledge of what Keycloak is and what is used for JWT knowledge

**Comment by m-bystrova** [comment]
### leetcode
- [ ] data structures: Queue, Tree
- [ ] Knows non-standard data structures like Table, Graph (Guava)
---

### petproject
- [ ] Knows REST principles, HTTP methods, HTTP vs HTTPS, JSON
- [ ] Serialize/deserialize Dates and times (incl. when using REST)
- [ ] Use out-of-the-box JSON/XML serialization tools
- [ ] Maven/Gradle
- [ ] Can configure projects with Maven/Gradle Configure additional plugins.
- [ ] Understands Maven/Gradle properties and profiles, can introduce and support conditional build steps
- [ ] Knows how Docker and Docker Compose works, basic commands and terms
- [ ] Work with a project that uses Hibernate
- [ ] Advanced Indexes knowledge
- [ ] Create custom images. Create docker-compose configurations. Read logs from container. Attach volumes
- [ ] Add Hibernate entities, uses Repository, creates queries
- [ ] Have experience in designing of REST  API methods from scratch, Open API 2/3, Swagger, Jackson
- [ ] OAuth knowledge Configure & use OAuth for project Knowledge of what Keycloak is and what is used for JWT knowledge
---

### java concurrency in practice
- [ ] thread and what is process
- [ ] Knows Threads, Executors API, synchronized. Can read and understand multithreaded code
- [ ] Knows how to use Blocking queues. Priority queues.
- [ ] Knows when volatile should be used. Understands locks and their behaviour. 
---

### design patterns
- [ ] basic design patterns
- [ ] Understanding basic concepts of SOLID and ACID
- [ ] Understanding of FIFO and LIFO principles
- [ ] Can explain how Creational Design Patterns can be used in real projects. Factory, Abstract Factory and etc.
- [ ] Experience in all types of design patterns (Creational, Structural, Behavioral) in real projects.
- [ ] Optimize code designs by using OOP principles
---

- [ ] functional programming
- [ ] Basic Reflection knowledge 
- [ ] Basic knowledge of how GC works
- [ ] Uses basic commands like less, grep, tail, head, find
- [ ] Strings memory allocation
- [ ] Know serialization process concept
- [ ] Can describe about stages and levels of garbage collection
- [ ] Have basic knowledge of NoSQL and differences between SQL and NoSQL
- [ ] Configure static code analysis tool
