### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by m-bystrova** [m-bystrova/learning#4]
2.12

- [x] https://www.youtube.com/watch?v=BmBr5diz8WA&list=PL6yLoZ_3Y0HKGL3F7vv2SNSrA3TkbXtBX&index=1

- [x] https://www.youtube.com/watch?v=cou_qomYLNU&list=PL6yLoZ_3Y0HKGL3F7vv2SNSrA3TkbXtBX&index=2

**Comment by m-bystrova** [comment]
- [ ] https://www.youtube.com/watch?v=rd6wxPzXQvo&list=PL6yLoZ_3Y0HKGL3F7vv2SNSrA3TkbXtBX&index=11

**Comment by m-bystrova** [comment]
21.12

- [ ] clean code
